var staticInterestedParties = {
    "interestedParties": [
        {
            "zipCode": "441303417",
            "contactId": "38749",
            "city": "Cleveland",
            "conEmail": "",
            "companyName": "Advanced Patient Advocacy",
            "contactFirstName": "Amy",
            "partyTypeCd": "AR",
            "conPhExt": "",
            "contactFullName": "Amy Hammond",
            "conPhone": "",
            "addressLine1": "18697 Bagley Rd",
            "msgText": "",
            "contactLastName": "Hammond",
            "addressLine2": "Rm 186",
            "state": "OH",
            "contactMiddleName": ""
        },
        {
            "zipCode": "45402",
            "contactId": "60379",
            "city": "Dayton",
            "conEmail": "HATS_NONPROD@jfs.ohio.gov",
            "companyName": "AAA PSA 3",
            "contactFirstName": "JOHN",
            "partyTypeCd": "AR",
            "conPhExt": "",
            "contactFullName": "",
            "conPhone": "6148675309",
            "addressLine1": "40 W 2ND ST",
            "msgText": "Participating by phone.",
            "contactLastName": "SMITH",
            "addressLine2": "",
            "state": "OH",
            "contactMiddleName": ""
        },
        {
            "zipCode": "444464820",
            "contactId": "31010",
            "city": "Niles",
            "conEmail": "bhagya.kalle@jfs.ohio.gov",
            "companyName": "Area Agency on Aging 11",
            "contactFirstName": "Jami",
            "partyTypeCd": "AR",
            "conPhExt": "",
            "contactFullName": "",
            "conPhone": "3305052322",
            "addressLine1": "5555 Youngstown Warren Rd",
            "msgText": "You have chosen to participate by phone in your state hearing and will be called at 330-505-2322. If this is not the correct number please contact the Bureau of State Hearings.",
            "contactLastName": "Gilronan",
            "addressLine2": "Unit 2685",
            "state": "OH",
            "contactMiddleName": ""
        }
    ],
    "opstatus": 0,
    "httpStatusCode": 200
};