
var dummyAppeals =    {"appealListByAppellant":    [
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341561",
    "portalProgramDesc": "Ohio Works First",
    "portalIssueCode": "Denial",
    "hearingDate": "11/30/2018",
    "portalStatus": "Open",
    "obPersonName": "DAKOTA HESTER",
    "dispositionId": 823682,
    "appealId": 1247062,
    "appealGroupId": 1480290
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341560",
    "portalProgramDesc": "Medicaid Eligibility Issues",
    "portalIssueCode": "Discontinuance - LTCF",
    "hearingDate": "11/30/2018",
    "portalStatus": "Open",
    "obPersonName": "MICHAEL HESTER",
    "dispositionId": 823681,
    "appealId": 1247061,
    "appealGroupId": 1480290
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341559",
    "portalProgramDesc": "Ohio Works First",
    "portalIssueCode": "Denial",
    "hearingDate": "11/30/2018",
    "portalStatus": "Open",
    "obPersonName": "HANNAH HESTER",
    "dispositionId": 823680,
    "appealId": 1247060,
    "appealGroupId": 1480290
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341558",
    "portalProgramDesc": "Medicaid Eligibility Issues",
    "portalIssueCode": "Discontinuance - ABD",
    "hearingDate": "11/30/2018",
    "portalStatus": "Open",
    "obPersonName": "GINA HESTER",
    "dispositionId": 823679,
    "appealId": 1247059,
    "appealGroupId": 1480290
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341557",
    "portalProgramDesc": "Ohio Works First",
    "portalIssueCode": "Denial",
    "hearingDate": "Not scheduled",
    "portalStatus": "Received",
    "obPersonName": "",
    "dispositionId": 823678,
    "appealId": 1247058,
    "appealGroupId": 1480288
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341556",
    "portalProgramDesc": "Medicaid",
    "portalIssueCode": "Unknown",
    "hearingDate": "Not scheduled",
    "portalStatus": "Received",
    "obPersonName": "",
    "dispositionId": 823677,
    "appealId": 1247057,
    "appealGroupId": 1480288
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341555",
    "portalProgramDesc": "Ohio Works First",
    "portalIssueCode": "Denial",
    "hearingDate": "Not scheduled",
    "portalStatus": "Received",
    "obPersonName": "",
    "dispositionId": 823676,
    "appealId": 1247056,
    "appealGroupId": 1480288
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341554",
    "portalProgramDesc": "Medicaid Services Issues",
    "portalIssueCode": "PASSPORT Waiver",
    "hearingDate": "Not scheduled",
    "portalStatus": "Received",
    "obPersonName": "",
    "dispositionId": 823675,
    "appealId": 1247055,
    "appealGroupId": 1480288
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341553",
    "portalProgramDesc": "Ohio Works First",
    "portalIssueCode": "Denial",
    "hearingDate": "Not scheduled",
    "portalStatus": "Received",
    "obPersonName": "",
    "dispositionId": 823674,
    "appealId": 1247054,
    "appealGroupId": 1480287
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341552",
    "portalProgramDesc": "Child Support",
    "portalIssueCode": "Denial - Administrative Review",
    "hearingDate": "Not scheduled",
    "portalStatus": "Received",
    "obPersonName": "",
    "dispositionId": 823673,
    "appealId": 1247053,
    "appealGroupId": 1480286
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341551",
    "portalProgramDesc": "Ohio Works First",
    "portalIssueCode": "Denial",
    "hearingDate": "Not scheduled",
    "portalStatus": "Received",
    "obPersonName": "",
    "dispositionId": 823672,
    "appealId": 1247052,
    "appealGroupId": 1480286
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341550",
    "portalProgramDesc": "Prevention Retention and Contingency",
    "portalIssueCode": "Benefit Amount",
    "hearingDate": "Not scheduled",
    "portalStatus": "Received",
    "obPersonName": "",
    "dispositionId": 823671,
    "appealId": 1247051,
    "appealGroupId": 1480286
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341549",
    "portalProgramDesc": "Ohio Works First",
    "portalIssueCode": "Denial",
    "hearingDate": "Not scheduled",
    "portalStatus": "Received",
    "obPersonName": "",
    "dispositionId": 823670,
    "appealId": 1247050,
    "appealGroupId": 1480285
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341548",
    "portalProgramDesc": "Medicaid Eligibility Issues",
    "portalIssueCode": "Approval - MAGI",
    "hearingDate": "Not scheduled",
    "portalStatus": "Received",
    "obPersonName": "",
    "dispositionId": 823669,
    "appealId": 1247049,
    "appealGroupId": 1480285
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341547",
    "portalProgramDesc": "Ohio Works First",
    "portalIssueCode": "Denial",
    "hearingDate": "Not scheduled",
    "portalStatus": "Received",
    "obPersonName": "",
    "dispositionId": 823668,
    "appealId": 1247048,
    "appealGroupId": 1480284
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341546",
    "portalProgramDesc": "Portal SNAP - SYS",
    "portalIssueCode": "Denial",
    "hearingDate": "Not scheduled",
    "portalStatus": "Received",
    "obPersonName": "",
    "dispositionId": 823667,
    "appealId": 1247047,
    "appealGroupId": 1480284
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341545",
    "portalProgramDesc": "Ohio Works First",
    "portalIssueCode": "Overpayment",
    "hearingDate": "Not scheduled",
    "portalStatus": "Open",
    "obPersonName": "",
    "dispositionId": 823666,
    "appealId": 1247046,
    "appealGroupId": 1480283
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341544",
    "portalProgramDesc": "Medicaid Services Issues",
    "portalIssueCode": "Delay - BCCP",
    "hearingDate": "Not scheduled",
    "portalStatus": "Open",
    "obPersonName": "",
    "dispositionId": 823665,
    "appealId": 1247045,
    "appealGroupId": 1480283
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341543",
    "portalProgramDesc": "Ohio Works First",
    "portalIssueCode": "Denial",
    "hearingDate": "Not scheduled",
    "portalStatus": "Open",
    "obPersonName": "",
    "dispositionId": 823664,
    "appealId": 1247044,
    "appealGroupId": 1480282
  },
  {
    "appealTypeDescription": "State Hearing",
    "appealNumber": "3341542",
    "portalProgramDesc": "Medicaid Eligibility Issues",
    "portalIssueCode": "Benefit Change - ABD",
    "hearingDate": "Not scheduled",
    "portalStatus": "Open",
    "obPersonName": "",
    "dispositionId": 823663,
    "appealId": 1247043,
    "appealGroupId": 1480282
  }
]};
