ALTER TABLE `server_timer_metrics_day1` MODIFY COLUMN `parent_service_name` varchar(455);
ALTER TABLE `server_timer_metrics_day2` MODIFY COLUMN `parent_service_name` varchar(455);
ALTER TABLE `server_timer_metrics_day3` MODIFY COLUMN `parent_service_name` varchar(455);
ALTER TABLE `server_timer_metrics_day4` MODIFY COLUMN `parent_service_name` varchar(455);
ALTER TABLE `server_timer_metrics_day5` MODIFY COLUMN `parent_service_name` varchar(455);
ALTER TABLE `server_timer_metrics_day6` MODIFY COLUMN `parent_service_name` varchar(455);
ALTER TABLE `server_timer_metrics_day7` MODIFY COLUMN `parent_service_name` varchar(455);
ALTER TABLE `server_timer_metrics_day8` MODIFY COLUMN `parent_service_name` varchar(455);
ALTER TABLE `server_timer_metrics_day9` MODIFY COLUMN `parent_service_name` varchar(455);