INSERT INTO metrics_configuration (name, value, created_date, updated_date) VALUES ('KONY_METRICS_GEOLOCATIONS_SUPPORT', 'false', CURDATE(), CURDATE());

-- Add new fields to geolocations_ip4_tmp table
ALTER TABLE geolocations_ip4_tmp
	ADD COLUMN countryName VARCHAR(255) AFTER country,
    ADD COLUMN regionName VARCHAR(255) AFTER region,
    ADD COLUMN continentCode VARCHAR(10) AFTER endIpInt,
    ADD COLUMN continentName VARCHAR(255) AFTER continentCode,
    ADD COLUMN timezone VARCHAR(255) AFTER dmacode,
    ADD COLUMN isInEuropeanUnion boolean AFTER timezone;
	
-- Modified length of region field
ALTER TABLE geolocations_ip4_tmp MODIFY COLUMN region VARCHAR(10);

DELIMITER ++
DROP PROCEDURE IF EXISTS CREATECOLUMNIFNOTEXISTS++

CREATE PROCEDURE CREATECOLUMNIFNOTEXISTS(TABLENAME VARCHAR(255), COLUMNNAME VARCHAR(255), DATATYPE VARCHAR(255), NOTNULL VARCHAR(255))
BEGIN
 /* create column if not exists */
 DECLARE EXIT HANDLER FOR SQLEXCEPTION, SQLWARNING BEGIN END;
 IF NOT EXISTS (SELECT * FROM information_schema.columns WHERE table_schema = '${KONY_REPORTS_DB}' and table_name COLLATE utf8_unicode_ci = TABLENAME and column_name COLLATE utf8_unicode_ci = COLUMNNAME) THEN
  SET @s = CONCAT("ALTER TABLE ", TABLENAME, " ADD COLUMN ", COLUMNNAME, " ", DATATYPE, " ", NOTNULL);
  PREPARE stmtd FROM @s;
  EXECUTE stmtd;
 END IF;
END++

DROP PROCEDURE IF EXISTS CREATESPATIALINDEXIFNOTEXISTS++

CREATE PROCEDURE CREATESPATIALINDEXIFNOTEXISTS(TABLENAME VARCHAR(255), INDEXNAME VARCHAR(255), COLUMNNAME VARCHAR(255))
BEGIN
 /* create index if not exists */
 DECLARE EXIT HANDLER FOR SQLEXCEPTION, SQLWARNING BEGIN END;
 IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.STATISTICS WHERE table_schema = '${KONY_REPORTS_DB}' and table_name COLLATE utf8_unicode_ci = TABLENAME and index_name COLLATE utf8_unicode_ci = INDEXNAME) THEN
  SET @s = CONCAT("ALTER TABLE ", TABLENAME, " ADD SPATIAL KEY ", INDEXNAME, " (", COLUMNNAME, ")");
  PREPARE stmtd FROM @s;
  EXECUTE stmtd;
 END IF;
END++

DELIMITER ;

COMMIT;