CREATE TABLE `SERVER_JOB_STATISTICS` (
  `JOB_STAT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `JOB_ID` bigint(20) NOT NULL ,
  `TOTAL_RUNS` bigint(20) NOT NULL ,
  `SUCCESS_RUNS` bigint(20) NOT NULL ,
  `FAILED_RUNS` bigint(20) NOT NULL ,
  `LAST_RUN_ELAPSED_TIME` bigint(20) NOT NULL ,
  `TOTAL_ELAPSED_TIME` bigint(20) NOT NULL ,
  `LAST_RUN_STATUS` varchar(100) NOT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`JOB_STAT_ID`),
  KEY `FK_SERVER_JOB_STATISTICS_JOB_ID` (`JOB_ID`),
  CONSTRAINT `FK_SERVER_JOB_STATISTICS_JOBID` FOREIGN KEY (`JOB_ID`) REFERENCES `SERVER_JOB` (`JOB_ID`) ON DELETE CASCADE
);