DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.expired.mail.bcc');
DELETE FROM `server_configuration` WHERE prop_name = 'license.expired.mail.bcc';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.expired.mail.cc');
DELETE FROM `server_configuration` WHERE prop_name = 'license.expired.mail.cc';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.expired.mail.content');
DELETE FROM `server_configuration` WHERE prop_name = 'license.expired.mail.content';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.expired.mail.recipients');
DELETE FROM `server_configuration` WHERE prop_name = 'license.expired.mail.recipients';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.expired.mail.replyto');
DELETE FROM `server_configuration` WHERE prop_name = 'license.expired.mail.replyto';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.expired.mail.subject');
DELETE FROM `server_configuration` WHERE prop_name = 'license.expired.mail.subject';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.expiry.warning.mail.bcc');
DELETE FROM `server_configuration` WHERE prop_name = 'license.expiry.warning.mail.bcc';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.expiry.warning.mail.cc');
DELETE FROM `server_configuration` WHERE prop_name = 'license.expiry.warning.mail.cc';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.expiry.warning.mail.content');
DELETE FROM `server_configuration` WHERE prop_name = 'license.expiry.warning.mail.content';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.expiry.warning.mail.recipients');
DELETE FROM `server_configuration` WHERE prop_name = 'license.expiry.warning.mail.recipients';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.expiry.warning.mail.replyto');
DELETE FROM `server_configuration` WHERE prop_name = 'license.expiry.warning.mail.replyto';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.expiry.warning.mail.subject');
DELETE FROM `server_configuration` WHERE prop_name = 'license.expiry.warning.mail.subject';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.file.path');
DELETE FROM `server_configuration` WHERE prop_name = 'license.file.path';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.mail.from');
DELETE FROM `server_configuration` WHERE prop_name = 'license.mail.from';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.mail.fromDisplayName');
DELETE FROM `server_configuration` WHERE prop_name = 'license.mail.fromDisplayName';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.mail.fromPwd');
DELETE FROM `server_configuration` WHERE prop_name = 'license.mail.fromPwd';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'license.mail.session.alert.threshold');
DELETE FROM `server_configuration` WHERE prop_name = 'license.mail.session.alert.threshold';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'mail.Provider.Impl');
DELETE FROM `server_configuration` WHERE prop_name = 'mail.Provider.Impl';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'mail.debug');
DELETE FROM `server_configuration` WHERE prop_name = 'mail.debug';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'mail.smtp.auth');
DELETE FROM `server_configuration` WHERE prop_name = 'mail.smtp.auth';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'mail.smtp.host');
DELETE FROM `server_configuration` WHERE prop_name = 'mail.smtp.host';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'mail.smtp.port');
DELETE FROM `server_configuration` WHERE prop_name = 'mail.smtp.port';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'mail.smtp.starttls.enable');
DELETE FROM `server_configuration` WHERE prop_name = 'mail.smtp.starttls.enable';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'session.limit.exceeded.mail.bcc');
DELETE FROM `server_configuration` WHERE prop_name = 'session.limit.exceeded.mail.bcc';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'session.limit.exceeded.mail.cc');
DELETE FROM `server_configuration` WHERE prop_name = 'session.limit.exceeded.mail.cc';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'session.limit.exceeded.mail.content');
DELETE FROM `server_configuration` WHERE prop_name = 'session.limit.exceeded.mail.content';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'session.limit.exceeded.mail.recipients');
DELETE FROM `server_configuration` WHERE prop_name = 'session.limit.exceeded.mail.recipients';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'session.limit.exceeded.mail.replyto');
DELETE FROM `server_configuration` WHERE prop_name = 'session.limit.exceeded.mail.replyto';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'session.limit.exceeded.mail.subject');
DELETE FROM `server_configuration` WHERE prop_name = 'session.limit.exceeded.mail.subject';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'session.limit.warning.mail.bcc');
DELETE FROM `server_configuration` WHERE prop_name = 'session.limit.warning.mail.bcc';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'session.limit.warning.mail.cc');
DELETE FROM `server_configuration` WHERE prop_name = 'session.limit.warning.mail.cc';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'session.limit.warning.mail.content');
DELETE FROM `server_configuration` WHERE prop_name = 'session.limit.warning.mail.content';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'session.limit.warning.mail.recipients');
DELETE FROM `server_configuration` WHERE prop_name = 'session.limit.warning.mail.recipients';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'session.limit.warning.mail.replyto');
DELETE FROM `server_configuration` WHERE prop_name = 'session.limit.warning.mail.replyto';
DELETE FROM `server_config_ui_metadata` WHERE `id` = (SELECT `id` FROM `server_configuration` WHERE `prop_name` = 'session.limit.warning.mail.subject');
DELETE FROM `server_configuration` WHERE prop_name = 'session.limit.warning.mail.subject';
