CREATE TABLE `server_timer_metrics` (
  `service_name` varchar(255) NOT NULL,
  `service_version` varchar(25) NOT NULL,
  `parent_service_name` varchar(255),
  `operation_name` varchar(255) NOT NULL,
  `service_category` varchar(35) NOT NULL,
  `service_type` varchar(35) NOT NULL,
  `verb` varchar(25) NOT NULL,
  `instance_id` varchar(35) NOT NULL,
  `count` int(10) unsigned DEFAULT NULL,
  `service_min` double(9,3) unsigned DEFAULT NULL,
  `service_max` double(9,3) unsigned DEFAULT NULL,
  `service_mean` double(9,3) unsigned DEFAULT NULL,
  `service_stddev` double(9,3) unsigned DEFAULT NULL,
  `pre_processor_min` double(9,3) unsigned DEFAULT NULL,
  `pre_processor_max` double(9,3) unsigned DEFAULT NULL,
  `pre_processor_mean` double(9,3) unsigned DEFAULT NULL,
  `pre_processor_stddev` double(9,3) unsigned DEFAULT NULL,
  `post_processor_min` double(9,3) unsigned DEFAULT NULL,
  `post_processor_max` double(9,3) unsigned DEFAULT NULL,
  `post_processor_mean` double(9,3) unsigned DEFAULT NULL,
  `post_processor_stddev` double(9,3) unsigned DEFAULT NULL,
  `request_mapper_min` double(9,3) unsigned DEFAULT NULL,
  `request_mapper_max` double(9,3) unsigned DEFAULT NULL,
  `request_mapper_mean` double(9,3) unsigned DEFAULT NULL,
  `request_mapper_stddev` double(9,3) unsigned DEFAULT NULL,
  `response_mapper_min` double(9,3) unsigned DEFAULT NULL,
  `response_mapper_max` double(9,3) unsigned DEFAULT NULL,
  `response_mapper_mean` double(9,3) unsigned DEFAULT NULL,
  `response_mapper_stddev` double(9,3) unsigned DEFAULT NULL,
  `backend_request_min` double(9,3) unsigned DEFAULT NULL,
  `backend_request_max` double(9,3) unsigned DEFAULT NULL,
  `backend_request_mean` double(9,3) unsigned DEFAULT NULL,
  `backend_request_stddev` double(9,3) unsigned DEFAULT NULL,
  `parsing_min` double(9,3) unsigned DEFAULT NULL,
  `parsing_max` double(9,3) unsigned DEFAULT NULL,
  `parsing_mean` double(9,3) unsigned DEFAULT NULL,
  `parsing_stddev` double(9,3) unsigned DEFAULT NULL,
  `url_provider_processing_min` double(9,3) unsigned DEFAULT NULL,
  `url_provider_processing_max` double(9,3) unsigned DEFAULT NULL,
  `url_provider_processing_mean` double(9,3) unsigned DEFAULT NULL,
  `url_provider_processing_stddev` double(9,3) unsigned DEFAULT NULL,
  `timestamp` timestamp NOT NULL,
  KEY `idx_servermetrics_inst_id` (`instance_id`),
  KEY `idx_servermetrics_ts` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;