ALTER TABLE `app_info` DROP INDEX application_id;
ALTER TABLE `app_info` ADD COLUMN `app_version` varchar(20) NOT NULL DEFAULT '1.0';
ALTER TABLE `app_info` ADD CONSTRAINT `uq_appid_version` UNIQUE(`application_id`, `app_version`);
ALTER TABLE `mobilefabric_configuration` MODIFY `prop_value` varchar(255) NULL;
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('richclient.deploy','${KONY_SERVER_RICH_CLIENT_DEPLOY}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('konycentral.datasource','java:comp/env/jdbc/KDCDB', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('konycentral.capabilitylist','j2me,markup,blackberry,info', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('controller.deffile','ControllerDef.xml', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('middleware.xssconfigfile','antisamy-1.3.xml', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('appregistry.dir','appregistry', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('fileupload.dir','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('memcache.cluster','${KONY_SERVER_MEMCACHE_CLUSTER}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('memcache.expiry','1200', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('memcache.storeattempts','12', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('memcache.retriveattempts','3', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('memcache.no.of.clients','${KONY_SERVER_MEMCACHED_COUNT}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('memcache.store.time','300', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('cacheid.transport','${KONY_SERVER_CACHEID_TRANSPORT}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('is.cacheid.cookie.secure','false', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('cacheid.cookie.path','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('use.encryption','false', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('ssl.trustStore','${KONY_SERVER_TRUSTSTORE_LOCATION}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('ssl.keyStore','${KONY_SERVER_KEYSTORE_LOCATION}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('ssl.trustStorePassword','${KONY_SERVER_TRUSTSTORE_PASSWORD}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('ssl.keyStorePassword','${KONY_SERVER_TRUSTSTORE_PASSWORD}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('ssl.keyStoreType','jks', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('ssl.trustStoreType','jks', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('ssl.algorithm','TLS', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('ssl.SocketFactory.provider','${KONY_SERVER_SSL_SOCKETFACTORY_PROVIDER}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('ssl.ServerSocketFactory.provider','${KONY_SERVER_SSL_SERVERSOCKETFACTORY_PROVIDER}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('ssl.SocketFactory.hostname.verifier','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('p.exclude','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('log.description.error','true', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('pubkey.file.path','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.file.path','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('mail.Provider.Impl','com.konylabs.middleware.common.mail.DefaultMailingProviderImpl', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('mail.smtp.host','smtp.exg5.exghost.com', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('mail.smtp.auth','true', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('mail.debug','true', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('mail.smtp.port','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('mail.smtp.starttls.enable','true', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.mail.from','sender@konylabs.com', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.mail.fromDisplayName','KONY', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.mail.fromPwd','default123', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.expiry.warning.mail.recipients','warningReceiver@konylabs.com', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.expiry.warning.mail.cc','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.expiry.warning.mail.bcc','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.expiry.warning.mail.replyto','info@kony.com', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.expired.mail.recipients','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.expired.mail.cc','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.expired.mail.bcc','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.expired.mail.replyto','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('session.limit.warning.mail.recipients','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('session.limit.warning.mail.cc','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('session.limit.warning.mail.bcc','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('session.limit.warning.mail.replyto','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('session.limit.exceeded.mail.recipients','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('session.limit.exceeded.mail.cc','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('session.limit.exceeded.mail.bcc','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('session.limit.exceeded.mail.replyto','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('metrics.URLPkgPrefixes','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.expiry.warning.mail.subject','Server license expiry warning', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.expiry.warning.mail.content','The server license is about to expire. Please get it renewed', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.expired.mail.subject','Server license has expired', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.expired.mail.content','The server license has already expired. Renew the license with priority to avail uninterrupted service', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('license.mail.session.alert.threshold','70', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('session.limit.warning.mail.subject','Session limit threshold has crossed', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('session.limit.warning.mail.content','Your usage of session has already crossed the threshold, please plan your refill of session in to your license', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('session.limit.exceeded.mail.subject','Already exceed the session maximum count', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('session.limit.exceeded.mail.content','The server has already used the allowed no of sessions, please refill your license with more sessions', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('do.not.log','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('send.default.user.agent','true', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('log.specific.session.attribute','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('log.specific.response.header','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('log.specific.request.header.parameter','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('ndc.delimiter','\n', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('mask.trace','false', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('mbeans.instantiation','false', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('gzipCompressionEnabled','true', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('maxHttpConnectionsPerHost','500', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('maxTotalHttpConnections','2000', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('dontEscapeXMLSpecialChars','', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('metrics.logging','true', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('metrics.TopicName','jms/KonyMetricsTopic', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('metrics.TopicConnectionFactoryName','jms/KonyConnectionFactory', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('metrics.initialContextFactoryName','${KONY_SERVER_JMS_INITIAL_CONTEXT_FACTORY}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('metrics.providerURL','${KONY_SERVER_JMS_PROVIDER_URL}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('metrics.securityPrincipalName','${KONY_SERVER_JMS_USER_NAME}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('metrics.securityCredentials','${KONY_SERVER_JMS_USER_PASSWORD}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('metrics.userName','${KONY_SERVER_JMS_USER_NAME}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('metrics.password','${KONY_SERVER_JMS_USER_PASSWORD}', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('jsonArraySupport','false', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('CORS_ENABLED','false', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('KONY_ACCOUNT_ID','Kony', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('ENVIRONMENT_ID','Dev', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('jms.logging','false', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('timer.period','10000', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('timer.delay','0', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('year.dropdown.offset','10', NOW() , NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('SERVER_LOG_LEVEL', 'ERROR', NOW(), NOW());
insert into `mobilefabric_configuration`(prop_name, prop_value, created_date , updated_date) values('SERVER_LOG_LOCATION', REPLACE('${KONY_SERVER_LOG_LOCATION}','#{', CONCAT('$','{')), NOW(), NOW());