INSERT INTO `server_configuration`(prop_name, prop_value, prop_type, created_date, updated_date) VALUES('KONY_SERVER_PERF_MEASUREMENT', 'true', 'ServerMonitoring', NOW(), NOW());

DROP TABLE `server_timer_metrics`;

CREATE TABLE `server_timer_metrics_day1` (
  `service_name` varchar(255) NOT NULL,
  `service_version` varchar(25) NOT NULL,
  `parent_service_name` varchar(255),
  `operation_name` varchar(255) NOT NULL,
  `service_category` varchar(35) NOT NULL,
  `service_type` varchar(35) NOT NULL,
  `verb` varchar(25) NOT NULL,
  `instance_id` varchar(35) NOT NULL,
  `count` int(10) unsigned,
  `service_min` int(10) unsigned,
  `service_max` int(10) unsigned,
  `service_mean` int(10) unsigned,
  `service_stddev` int(10) unsigned,
  `pre_processor_min` int(10) unsigned,
  `pre_processor_max` int(10) unsigned,
  `pre_processor_mean` int(10) unsigned,
  `pre_processor_stddev` int(10) unsigned,
  `post_processor_min` int(10) unsigned,
  `post_processor_max` int(10) unsigned,
  `post_processor_mean` int(10) unsigned,
  `post_processor_stddev` int(10) unsigned,
  `request_mapper_min` int(10) unsigned,
  `request_mapper_max` int(10) unsigned,
  `request_mapper_mean` int(10) unsigned,
  `request_mapper_stddev` int(10) unsigned,
  `response_mapper_min` int(10) unsigned,
  `response_mapper_max` int(10) unsigned,
  `response_mapper_mean` int(10) unsigned,
  `response_mapper_stddev` int(10) unsigned,
  `backend_request_min` int(10) unsigned,
  `backend_request_max` int(10) unsigned,
  `backend_request_mean` int(10) unsigned,
  `backend_request_stddev` int(10) unsigned,
  `parsing_min` int(10) unsigned,
  `parsing_max` int(10) unsigned,
  `parsing_mean` int(10) unsigned,
  `parsing_stddev` int(10) unsigned,
  `url_provider_processing_min` int(10) unsigned,
  `url_provider_processing_max` int(10) unsigned,
  `url_provider_processing_mean` int(10) unsigned,
  `url_provider_processing_stddev` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_servermetrics_insid_day1` (`instance_id`),
  KEY `idx_servermetrics_ts_day1` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_timer_metrics_day2` (
  `service_name` varchar(255) NOT NULL,
  `service_version` varchar(25) NOT NULL,
  `parent_service_name` varchar(255),
  `operation_name` varchar(255) NOT NULL,
  `service_category` varchar(35) NOT NULL,
  `service_type` varchar(35) NOT NULL,
  `verb` varchar(25) NOT NULL,
  `instance_id` varchar(35) NOT NULL,
  `count` int(10) unsigned,
  `service_min` int(10) unsigned,
  `service_max` int(10) unsigned,
  `service_mean` int(10) unsigned,
  `service_stddev` int(10) unsigned,
  `pre_processor_min` int(10) unsigned,
  `pre_processor_max` int(10) unsigned,
  `pre_processor_mean` int(10) unsigned,
  `pre_processor_stddev` int(10) unsigned,
  `post_processor_min` int(10) unsigned,
  `post_processor_max` int(10) unsigned,
  `post_processor_mean` int(10) unsigned,
  `post_processor_stddev` int(10) unsigned,
  `request_mapper_min` int(10) unsigned,
  `request_mapper_max` int(10) unsigned,
  `request_mapper_mean` int(10) unsigned,
  `request_mapper_stddev` int(10) unsigned,
  `response_mapper_min` int(10) unsigned,
  `response_mapper_max` int(10) unsigned,
  `response_mapper_mean` int(10) unsigned,
  `response_mapper_stddev` int(10) unsigned,
  `backend_request_min` int(10) unsigned,
  `backend_request_max` int(10) unsigned,
  `backend_request_mean` int(10) unsigned,
  `backend_request_stddev` int(10) unsigned,
  `parsing_min` int(10) unsigned,
  `parsing_max` int(10) unsigned,
  `parsing_mean` int(10) unsigned,
  `parsing_stddev` int(10) unsigned,
  `url_provider_processing_min` int(10) unsigned,
  `url_provider_processing_max` int(10) unsigned,
  `url_provider_processing_mean` int(10) unsigned,
  `url_provider_processing_stddev` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_servermetrics_insid_day2` (`instance_id`),
  KEY `idx_servermetrics_ts_day2` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_timer_metrics_day3` (
  `service_name` varchar(255) NOT NULL,
  `service_version` varchar(25) NOT NULL,
  `parent_service_name` varchar(255),
  `operation_name` varchar(255) NOT NULL,
  `service_category` varchar(35) NOT NULL,
  `service_type` varchar(35) NOT NULL,
  `verb` varchar(25) NOT NULL,
  `instance_id` varchar(35) NOT NULL,
  `count` int(10) unsigned,
  `service_min` int(10) unsigned,
  `service_max` int(10) unsigned,
  `service_mean` int(10) unsigned,
  `service_stddev` int(10) unsigned,
  `pre_processor_min` int(10) unsigned,
  `pre_processor_max` int(10) unsigned,
  `pre_processor_mean` int(10) unsigned,
  `pre_processor_stddev` int(10) unsigned,
  `post_processor_min` int(10) unsigned,
  `post_processor_max` int(10) unsigned,
  `post_processor_mean` int(10) unsigned,
  `post_processor_stddev` int(10) unsigned,
  `request_mapper_min` int(10) unsigned,
  `request_mapper_max` int(10) unsigned,
  `request_mapper_mean` int(10) unsigned,
  `request_mapper_stddev` int(10) unsigned,
  `response_mapper_min` int(10) unsigned,
  `response_mapper_max` int(10) unsigned,
  `response_mapper_mean` int(10) unsigned,
  `response_mapper_stddev` int(10) unsigned,
  `backend_request_min` int(10) unsigned,
  `backend_request_max` int(10) unsigned,
  `backend_request_mean` int(10) unsigned,
  `backend_request_stddev` int(10) unsigned,
  `parsing_min` int(10) unsigned,
  `parsing_max` int(10) unsigned,
  `parsing_mean` int(10) unsigned,
  `parsing_stddev` int(10) unsigned,
  `url_provider_processing_min` int(10) unsigned,
  `url_provider_processing_max` int(10) unsigned,
  `url_provider_processing_mean` int(10) unsigned,
  `url_provider_processing_stddev` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_servermetrics_insid_day3` (`instance_id`),
  KEY `idx_servermetrics_ts_day3` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_timer_metrics_day4` (
  `service_name` varchar(255) NOT NULL,
  `service_version` varchar(25) NOT NULL,
  `parent_service_name` varchar(255),
  `operation_name` varchar(255) NOT NULL,
  `service_category` varchar(35) NOT NULL,
  `service_type` varchar(35) NOT NULL,
  `verb` varchar(25) NOT NULL,
  `instance_id` varchar(35) NOT NULL,
  `count` int(10) unsigned,
  `service_min` int(10) unsigned,
  `service_max` int(10) unsigned,
  `service_mean` int(10) unsigned,
  `service_stddev` int(10) unsigned,
  `pre_processor_min` int(10) unsigned,
  `pre_processor_max` int(10) unsigned,
  `pre_processor_mean` int(10) unsigned,
  `pre_processor_stddev` int(10) unsigned,
  `post_processor_min` int(10) unsigned,
  `post_processor_max` int(10) unsigned,
  `post_processor_mean` int(10) unsigned,
  `post_processor_stddev` int(10) unsigned,
  `request_mapper_min` int(10) unsigned,
  `request_mapper_max` int(10) unsigned,
  `request_mapper_mean` int(10) unsigned,
  `request_mapper_stddev` int(10) unsigned,
  `response_mapper_min` int(10) unsigned,
  `response_mapper_max` int(10) unsigned,
  `response_mapper_mean` int(10) unsigned,
  `response_mapper_stddev` int(10) unsigned,
  `backend_request_min` int(10) unsigned,
  `backend_request_max` int(10) unsigned,
  `backend_request_mean` int(10) unsigned,
  `backend_request_stddev` int(10) unsigned,
  `parsing_min` int(10) unsigned,
  `parsing_max` int(10) unsigned,
  `parsing_mean` int(10) unsigned,
  `parsing_stddev` int(10) unsigned,
  `url_provider_processing_min` int(10) unsigned,
  `url_provider_processing_max` int(10) unsigned,
  `url_provider_processing_mean` int(10) unsigned,
  `url_provider_processing_stddev` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_servermetrics_insid_day4` (`instance_id`),
  KEY `idx_servermetrics_ts_day4` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_timer_metrics_day5` (
  `service_name` varchar(255) NOT NULL,
  `service_version` varchar(25) NOT NULL,
  `parent_service_name` varchar(255),
  `operation_name` varchar(255) NOT NULL,
  `service_category` varchar(35) NOT NULL,
  `service_type` varchar(35) NOT NULL,
  `verb` varchar(25) NOT NULL,
  `instance_id` varchar(35) NOT NULL,
  `count` int(10) unsigned,
  `service_min` int(10) unsigned,
  `service_max` int(10) unsigned,
  `service_mean` int(10) unsigned,
  `service_stddev` int(10) unsigned,
  `pre_processor_min` int(10) unsigned,
  `pre_processor_max` int(10) unsigned,
  `pre_processor_mean` int(10) unsigned,
  `pre_processor_stddev` int(10) unsigned,
  `post_processor_min` int(10) unsigned,
  `post_processor_max` int(10) unsigned,
  `post_processor_mean` int(10) unsigned,
  `post_processor_stddev` int(10) unsigned,
  `request_mapper_min` int(10) unsigned,
  `request_mapper_max` int(10) unsigned,
  `request_mapper_mean` int(10) unsigned,
  `request_mapper_stddev` int(10) unsigned,
  `response_mapper_min` int(10) unsigned,
  `response_mapper_max` int(10) unsigned,
  `response_mapper_mean` int(10) unsigned,
  `response_mapper_stddev` int(10) unsigned,
  `backend_request_min` int(10) unsigned,
  `backend_request_max` int(10) unsigned,
  `backend_request_mean` int(10) unsigned,
  `backend_request_stddev` int(10) unsigned,
  `parsing_min` int(10) unsigned,
  `parsing_max` int(10) unsigned,
  `parsing_mean` int(10) unsigned,
  `parsing_stddev` int(10) unsigned,
  `url_provider_processing_min` int(10) unsigned,
  `url_provider_processing_max` int(10) unsigned,
  `url_provider_processing_mean` int(10) unsigned,
  `url_provider_processing_stddev` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_servermetrics_insid_day5` (`instance_id`),
  KEY `idx_servermetrics_ts_day5` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_timer_metrics_day6` (
  `service_name` varchar(255) NOT NULL,
  `service_version` varchar(25) NOT NULL,
  `parent_service_name` varchar(255),
  `operation_name` varchar(255) NOT NULL,
  `service_category` varchar(35) NOT NULL,
  `service_type` varchar(35) NOT NULL,
  `verb` varchar(25) NOT NULL,
  `instance_id` varchar(35) NOT NULL,
  `count` int(10) unsigned,
  `service_min` int(10) unsigned,
  `service_max` int(10) unsigned,
  `service_mean` int(10) unsigned,
  `service_stddev` int(10) unsigned,
  `pre_processor_min` int(10) unsigned,
  `pre_processor_max` int(10) unsigned,
  `pre_processor_mean` int(10) unsigned,
  `pre_processor_stddev` int(10) unsigned,
  `post_processor_min` int(10) unsigned,
  `post_processor_max` int(10) unsigned,
  `post_processor_mean` int(10) unsigned,
  `post_processor_stddev` int(10) unsigned,
  `request_mapper_min` int(10) unsigned,
  `request_mapper_max` int(10) unsigned,
  `request_mapper_mean` int(10) unsigned,
  `request_mapper_stddev` int(10) unsigned,
  `response_mapper_min` int(10) unsigned,
  `response_mapper_max` int(10) unsigned,
  `response_mapper_mean` int(10) unsigned,
  `response_mapper_stddev` int(10) unsigned,
  `backend_request_min` int(10) unsigned,
  `backend_request_max` int(10) unsigned,
  `backend_request_mean` int(10) unsigned,
  `backend_request_stddev` int(10) unsigned,
  `parsing_min` int(10) unsigned,
  `parsing_max` int(10) unsigned,
  `parsing_mean` int(10) unsigned,
  `parsing_stddev` int(10) unsigned,
  `url_provider_processing_min` int(10) unsigned,
  `url_provider_processing_max` int(10) unsigned,
  `url_provider_processing_mean` int(10) unsigned,
  `url_provider_processing_stddev` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_servermetrics_insid_day6` (`instance_id`),
  KEY `idx_servermetrics_ts_day6` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_timer_metrics_day7` (
  `service_name` varchar(255) NOT NULL,
  `service_version` varchar(25) NOT NULL,
  `parent_service_name` varchar(255),
  `operation_name` varchar(255) NOT NULL,
  `service_category` varchar(35) NOT NULL,
  `service_type` varchar(35) NOT NULL,
  `verb` varchar(25) NOT NULL,
  `instance_id` varchar(35) NOT NULL,
  `count` int(10) unsigned,
  `service_min` int(10) unsigned,
  `service_max` int(10) unsigned,
  `service_mean` int(10) unsigned,
  `service_stddev` int(10) unsigned,
  `pre_processor_min` int(10) unsigned,
  `pre_processor_max` int(10) unsigned,
  `pre_processor_mean` int(10) unsigned,
  `pre_processor_stddev` int(10) unsigned,
  `post_processor_min` int(10) unsigned,
  `post_processor_max` int(10) unsigned,
  `post_processor_mean` int(10) unsigned,
  `post_processor_stddev` int(10) unsigned,
  `request_mapper_min` int(10) unsigned,
  `request_mapper_max` int(10) unsigned,
  `request_mapper_mean` int(10) unsigned,
  `request_mapper_stddev` int(10) unsigned,
  `response_mapper_min` int(10) unsigned,
  `response_mapper_max` int(10) unsigned,
  `response_mapper_mean` int(10) unsigned,
  `response_mapper_stddev` int(10) unsigned,
  `backend_request_min` int(10) unsigned,
  `backend_request_max` int(10) unsigned,
  `backend_request_mean` int(10) unsigned,
  `backend_request_stddev` int(10) unsigned,
  `parsing_min` int(10) unsigned,
  `parsing_max` int(10) unsigned,
  `parsing_mean` int(10) unsigned,
  `parsing_stddev` int(10) unsigned,
  `url_provider_processing_min` int(10) unsigned,
  `url_provider_processing_max` int(10) unsigned,
  `url_provider_processing_mean` int(10) unsigned,
  `url_provider_processing_stddev` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_servermetrics_insid_day7` (`instance_id`),
  KEY `idx_servermetrics_ts_day7` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_timer_metrics_day8` (
  `service_name` varchar(255) NOT NULL,
  `service_version` varchar(25) NOT NULL,
  `parent_service_name` varchar(255),
  `operation_name` varchar(255) NOT NULL,
  `service_category` varchar(35) NOT NULL,
  `service_type` varchar(35) NOT NULL,
  `verb` varchar(25) NOT NULL,
  `instance_id` varchar(35) NOT NULL,
  `count` int(10) unsigned,
  `service_min` int(10) unsigned,
  `service_max` int(10) unsigned,
  `service_mean` int(10) unsigned,
  `service_stddev` int(10) unsigned,
  `pre_processor_min` int(10) unsigned,
  `pre_processor_max` int(10) unsigned,
  `pre_processor_mean` int(10) unsigned,
  `pre_processor_stddev` int(10) unsigned,
  `post_processor_min` int(10) unsigned,
  `post_processor_max` int(10) unsigned,
  `post_processor_mean` int(10) unsigned,
  `post_processor_stddev` int(10) unsigned,
  `request_mapper_min` int(10) unsigned,
  `request_mapper_max` int(10) unsigned,
  `request_mapper_mean` int(10) unsigned,
  `request_mapper_stddev` int(10) unsigned,
  `response_mapper_min` int(10) unsigned,
  `response_mapper_max` int(10) unsigned,
  `response_mapper_mean` int(10) unsigned,
  `response_mapper_stddev` int(10) unsigned,
  `backend_request_min` int(10) unsigned,
  `backend_request_max` int(10) unsigned,
  `backend_request_mean` int(10) unsigned,
  `backend_request_stddev` int(10) unsigned,
  `parsing_min` int(10) unsigned,
  `parsing_max` int(10) unsigned,
  `parsing_mean` int(10) unsigned,
  `parsing_stddev` int(10) unsigned,
  `url_provider_processing_min` int(10) unsigned,
  `url_provider_processing_max` int(10) unsigned,
  `url_provider_processing_mean` int(10) unsigned,
  `url_provider_processing_stddev` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_servermetrics_insid_day8` (`instance_id`),
  KEY `idx_servermetrics_ts_day8` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_timer_metrics_day9` (
  `service_name` varchar(255) NOT NULL,
  `service_version` varchar(25) NOT NULL,
  `parent_service_name` varchar(255),
  `operation_name` varchar(255) NOT NULL,
  `service_category` varchar(35) NOT NULL,
  `service_type` varchar(35) NOT NULL,
  `verb` varchar(25) NOT NULL,
  `instance_id` varchar(35) NOT NULL,
  `count` int(10) unsigned,
  `service_min` int(10) unsigned,
  `service_max` int(10) unsigned,
  `service_mean` int(10) unsigned,
  `service_stddev` int(10) unsigned,
  `pre_processor_min` int(10) unsigned,
  `pre_processor_max` int(10) unsigned,
  `pre_processor_mean` int(10) unsigned,
  `pre_processor_stddev` int(10) unsigned,
  `post_processor_min` int(10) unsigned,
  `post_processor_max` int(10) unsigned,
  `post_processor_mean` int(10) unsigned,
  `post_processor_stddev` int(10) unsigned,
  `request_mapper_min` int(10) unsigned,
  `request_mapper_max` int(10) unsigned,
  `request_mapper_mean` int(10) unsigned,
  `request_mapper_stddev` int(10) unsigned,
  `response_mapper_min` int(10) unsigned,
  `response_mapper_max` int(10) unsigned,
  `response_mapper_mean` int(10) unsigned,
  `response_mapper_stddev` int(10) unsigned,
  `backend_request_min` int(10) unsigned,
  `backend_request_max` int(10) unsigned,
  `backend_request_mean` int(10) unsigned,
  `backend_request_stddev` int(10) unsigned,
  `parsing_min` int(10) unsigned,
  `parsing_max` int(10) unsigned,
  `parsing_mean` int(10) unsigned,
  `parsing_stddev` int(10) unsigned,
  `url_provider_processing_min` int(10) unsigned,
  `url_provider_processing_max` int(10) unsigned,
  `url_provider_processing_mean` int(10) unsigned,
  `url_provider_processing_stddev` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_servermetrics_insid_day9` (`instance_id`),
  KEY `idx_servermetrics_ts_day9` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE VIEW server_timer_metrics AS 
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day1
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day2
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day3
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day4
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day5
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day6
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day7
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day8
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day9
;