ALTER TABLE `server_application_log` ADD column `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE `server_timer_metrics_day1` ADD column `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `server_timer_metrics_day1` ADD column `error_count` int(10) unsigned;

ALTER TABLE `server_timer_metrics_day2` ADD column `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `server_timer_metrics_day2` ADD column `error_count` int(10) unsigned;

ALTER TABLE `server_timer_metrics_day3` ADD column `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `server_timer_metrics_day3` ADD column `error_count` int(10) unsigned;

ALTER TABLE `server_timer_metrics_day4` ADD column `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `server_timer_metrics_day4` ADD column `error_count` int(10) unsigned;

ALTER TABLE `server_timer_metrics_day5` ADD column `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `server_timer_metrics_day5` ADD column `error_count` int(10) unsigned;

ALTER TABLE `server_timer_metrics_day6` ADD column `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `server_timer_metrics_day6` ADD column `error_count` int(10) unsigned;

ALTER TABLE `server_timer_metrics_day7` ADD column `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `server_timer_metrics_day7` ADD column `error_count` int(10) unsigned;

ALTER TABLE `server_timer_metrics_day8` ADD column `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `server_timer_metrics_day8` ADD column `error_count` int(10) unsigned;

ALTER TABLE `server_timer_metrics_day9` ADD column `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `server_timer_metrics_day9` ADD column `error_count` int(10) unsigned;

DROP VIEW server_timer_metrics;
CREATE VIEW server_timer_metrics AS 
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	error_count AS error_count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day1
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	error_count AS error_count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day2
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	error_count AS error_count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day3
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	error_count AS error_count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day4
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	error_count AS error_count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day5
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	error_count AS error_count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day6
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	error_count AS error_count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day7
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	error_count AS error_count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day8
UNION
SELECT
	service_name AS service_name,
	service_version AS service_version,
	parent_service_name AS parent_service_name,
	operation_name AS operation_name,
	service_category AS service_category,
	service_type AS service_type,
	verb AS verb,
	instance_id AS instance_id,
	count AS count,
	error_count AS error_count,
	service_min AS service_min,
	service_max AS service_max,
	service_mean AS service_mean,
	service_stddev AS service_stddev,
	pre_processor_min AS pre_processor_min,
	pre_processor_max AS pre_processor_max,
	pre_processor_mean AS pre_processor_mean,
	pre_processor_stddev AS pre_processor_stddev,
	post_processor_min AS post_processor_min,
	post_processor_max AS post_processor_max,
	post_processor_mean AS post_processor_mean,
	post_processor_stddev AS post_processor_stddev,
	request_mapper_min AS request_mapper_min,
	request_mapper_max AS request_mapper_max,
	request_mapper_mean AS request_mapper_mean,
	request_mapper_stddev AS request_mapper_stddev,
	response_mapper_min AS response_mapper_min,
	response_mapper_max AS response_mapper_max,
	response_mapper_mean AS response_mapper_mean,
	response_mapper_stddev AS response_mapper_stddev,
	backend_request_min AS backend_request_min,
	backend_request_max AS backend_request_max,
	backend_request_mean AS backend_request_mean,
	backend_request_stddev AS backend_request_stddev,
	parsing_min AS parsing_min,
	parsing_max AS parsing_max,
	parsing_mean AS parsing_mean,
	parsing_stddev AS parsing_stddev,
	url_provider_processing_min AS url_provider_processing_min,
	url_provider_processing_max AS url_provider_processing_max,
	url_provider_processing_mean AS url_provider_processing_mean,
	url_provider_processing_stddev AS url_provider_processing_stddev,
	timestamp AS timestamp
	FROM server_timer_metrics_day9
;