INSERT INTO `server_configuration`(prop_name, prop_value, prop_type, created_date, updated_date) VALUES('KONY_SERVER_ENVIRONMENT_MONITORING', 'true', 'ServerMonitoring', NOW(), NOW());
INSERT INTO `server_configuration`(prop_name, prop_value, prop_type, created_date, updated_date) VALUES('KONY_SERVER_SHOW_ENVIRONMENT_MONITORING_DATA', '${KONY_SERVER_SHOW_ENVIRONMENT_MONITORING_DATA}', 'ServerMonitoring', NOW(), NOW());

CREATE TABLE server_env_metrics_day1 (
	`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`instance_id` varchar(35) NOT NULL,
	`cpu_load` DECIMAL(5,2),
	`memory_total_init` int(10),
	`memory_total_max` int(10),
	`memory_total_used` int(10),
	`memory_total_committed` int(10),
	`memory_heap_init` int(10),
	`memory_heap_max` int(10),
	`memory_heap_used` int(10),
	`memory_heap_committed` int(10),
	`memory_non_heap_init` int(10),
	`memory_non_heap_max` int(10),
	`memory_non_heap_used` int(10),
	`memory_non_heap_committed` int(10),
	`thread_count` int(10),
	`thread_runnable_count` int(10),
	`thread_blocked_count` int(10),
	`thread_deadlock_count` int(10),
	`timestamp` timestamp NOT NULL,
	KEY `idx_envmetrics_insid_day1` (`instance_id`),
	KEY `idx_envmetrics_ts_day1` (`timestamp`),
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE server_env_metrics_day2 (
	`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`instance_id` varchar(35) NOT NULL,
	`cpu_load` DECIMAL(5,2),
	`memory_total_init` int(10),
	`memory_total_max` int(10),
	`memory_total_used` int(10),
	`memory_total_committed` int(10),
	`memory_heap_init` int(10),
	`memory_heap_max` int(10),
	`memory_heap_used` int(10),
	`memory_heap_committed` int(10),
	`memory_non_heap_init` int(10),
	`memory_non_heap_max` int(10),
	`memory_non_heap_used` int(10),
	`memory_non_heap_committed` int(10),
	`thread_count` int(10),
	`thread_runnable_count` int(10),
	`thread_blocked_count` int(10),
	`thread_deadlock_count` int(10),
	`timestamp` timestamp NOT NULL,
	KEY `idx_envmetrics_insid_day2` (`instance_id`),
	KEY `idx_envmetrics_ts_day2` (`timestamp`),
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE server_env_metrics_day3 (
	`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`instance_id` varchar(35) NOT NULL,
	`cpu_load` DECIMAL(5,2),
	`memory_total_init` int(10),
	`memory_total_max` int(10),
	`memory_total_used` int(10),
	`memory_total_committed` int(10),
	`memory_heap_init` int(10),
	`memory_heap_max` int(10),
	`memory_heap_used` int(10),
	`memory_heap_committed` int(10),
	`memory_non_heap_init` int(10),
	`memory_non_heap_max` int(10),
	`memory_non_heap_used` int(10),
	`memory_non_heap_committed` int(10),
	`thread_count` int(10),
	`thread_runnable_count` int(10),
	`thread_blocked_count` int(10),
	`thread_deadlock_count` int(10),
	`timestamp` timestamp NOT NULL,
	KEY `idx_envmetrics_insid_day3` (`instance_id`),
	KEY `idx_envmetrics_ts_day3` (`timestamp`),
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE server_env_metrics_day4 (
	`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`instance_id` varchar(35) NOT NULL,
	`cpu_load` DECIMAL(5,2),
	`memory_total_init` int(10),
	`memory_total_max` int(10),
	`memory_total_used` int(10),
	`memory_total_committed` int(10),
	`memory_heap_init` int(10),
	`memory_heap_max` int(10),
	`memory_heap_used` int(10),
	`memory_heap_committed` int(10),
	`memory_non_heap_init` int(10),
	`memory_non_heap_max` int(10),
	`memory_non_heap_used` int(10),
	`memory_non_heap_committed` int(10),
	`thread_count` int(10),
	`thread_runnable_count` int(10),
	`thread_blocked_count` int(10),
	`thread_deadlock_count` int(10),
	`timestamp` timestamp NOT NULL,
	KEY `idx_envmetrics_insid_day4` (`instance_id`),
	KEY `idx_envmetrics_ts_day4` (`timestamp`),
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE server_env_metrics_day5 (
	`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`instance_id` varchar(35) NOT NULL,
	`cpu_load` DECIMAL(5,2),
	`memory_total_init` int(10),
	`memory_total_max` int(10),
	`memory_total_used` int(10),
	`memory_total_committed` int(10),
	`memory_heap_init` int(10),
	`memory_heap_max` int(10),
	`memory_heap_used` int(10),
	`memory_heap_committed` int(10),
	`memory_non_heap_init` int(10),
	`memory_non_heap_max` int(10),
	`memory_non_heap_used` int(10),
	`memory_non_heap_committed` int(10),
	`thread_count` int(10),
	`thread_runnable_count` int(10),
	`thread_blocked_count` int(10),
	`thread_deadlock_count` int(10),
	`timestamp` timestamp NOT NULL,
	KEY `idx_envmetrics_insid_day5` (`instance_id`),
	KEY `idx_envmetrics_ts_day5` (`timestamp`),
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE server_env_metrics_day6 (
	`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`instance_id` varchar(35) NOT NULL,
	`cpu_load` DECIMAL(5,2),
	`memory_total_init` int(10),
	`memory_total_max` int(10),
	`memory_total_used` int(10),
	`memory_total_committed` int(10),
	`memory_heap_init` int(10),
	`memory_heap_max` int(10),
	`memory_heap_used` int(10),
	`memory_heap_committed` int(10),
	`memory_non_heap_init` int(10),
	`memory_non_heap_max` int(10),
	`memory_non_heap_used` int(10),
	`memory_non_heap_committed` int(10),
	`thread_count` int(10),
	`thread_runnable_count` int(10),
	`thread_blocked_count` int(10),
	`thread_deadlock_count` int(10),
	`timestamp` timestamp NOT NULL,
	KEY `idx_envmetrics_insid_day6` (`instance_id`),
	KEY `idx_envmetrics_ts_day6` (`timestamp`),
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE server_env_metrics_day7 (
	`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`instance_id` varchar(35) NOT NULL,
	`cpu_load` DECIMAL(5,2),
	`memory_total_init` int(10),
	`memory_total_max` int(10),
	`memory_total_used` int(10),
	`memory_total_committed` int(10),
	`memory_heap_init` int(10),
	`memory_heap_max` int(10),
	`memory_heap_used` int(10),
	`memory_heap_committed` int(10),
	`memory_non_heap_init` int(10),
	`memory_non_heap_max` int(10),
	`memory_non_heap_used` int(10),
	`memory_non_heap_committed` int(10),
	`thread_count` int(10),
	`thread_runnable_count` int(10),
	`thread_blocked_count` int(10),
	`thread_deadlock_count` int(10),
	`timestamp` timestamp NOT NULL,
	KEY `idx_envmetrics_insid_day7` (`instance_id`),
	KEY `idx_envmetrics_ts_day7` (`timestamp`),
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE server_env_metrics_day8 (
	`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`instance_id` varchar(35) NOT NULL,
	`cpu_load` DECIMAL(5,2),
	`memory_total_init` int(10),
	`memory_total_max` int(10),
	`memory_total_used` int(10),
	`memory_total_committed` int(10),
	`memory_heap_init` int(10),
	`memory_heap_max` int(10),
	`memory_heap_used` int(10),
	`memory_heap_committed` int(10),
	`memory_non_heap_init` int(10),
	`memory_non_heap_max` int(10),
	`memory_non_heap_used` int(10),
	`memory_non_heap_committed` int(10),
	`thread_count` int(10),
	`thread_runnable_count` int(10),
	`thread_blocked_count` int(10),
	`thread_deadlock_count` int(10),
	`timestamp` timestamp NOT NULL,
	KEY `idx_envmetrics_insid_day8` (`instance_id`),
	KEY `idx_envmetrics_ts_day8` (`timestamp`),
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE server_env_metrics_day9 (
	`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`instance_id` varchar(35) NOT NULL,
	`cpu_load` DECIMAL(5,2),
	`memory_total_init` int(10),
	`memory_total_max` int(10),
	`memory_total_used` int(10),
	`memory_total_committed` int(10),
	`memory_heap_init` int(10),
	`memory_heap_max` int(10),
	`memory_heap_used` int(10),
	`memory_heap_committed` int(10),
	`memory_non_heap_init` int(10),
	`memory_non_heap_max` int(10),
	`memory_non_heap_used` int(10),
	`memory_non_heap_committed` int(10),
	`thread_count` int(10),
	`thread_runnable_count` int(10),
	`thread_blocked_count` int(10),
	`thread_deadlock_count` int(10),
	`timestamp` timestamp NOT NULL,
	KEY `idx_envmetrics_insid_day9` (`instance_id`),
	KEY `idx_envmetrics_ts_day9` (`timestamp`),
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

COMMIT;