CREATE TABLE `server_event_metrics_day1` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `event_name` varchar(255) NOT NULL,
  `event_type` varchar(255),
  `event_source` varchar(255),
  `app_name` varchar(255),
  `instance_id` varchar(35) NOT NULL,
  `subscribers_count` int(10) unsigned,
  `queued_count` int(10) unsigned,
  `processed_count` int(10) unsigned,
  `subscribers_error_count` int(10) unsigned,
  `event_delivery_time_min` int(10) unsigned,
  `event_delivery_time_max` int(10) unsigned,
  `event_delivery_time_mean` int(10) unsigned,
  `event_queue_time_min` int(10) unsigned,
  `event_queue_time_max` int(10) unsigned,
  `event_queue_time_mean` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_event_insid_day1` (`instance_id`),
  KEY `idx_event_ts_day1` (`timestamp`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_event_metrics_day2` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `event_name` varchar(255) NOT NULL,
  `event_type` varchar(255),
  `event_source` varchar(255),
  `app_name` varchar(255),
  `instance_id` varchar(35) NOT NULL,
  `subscribers_count` int(10) unsigned,
  `queued_count` int(10) unsigned,
  `processed_count` int(10) unsigned,
  `subscribers_error_count` int(10) unsigned,
  `event_delivery_time_min` int(10) unsigned,
  `event_delivery_time_max` int(10) unsigned,
  `event_delivery_time_mean` int(10) unsigned,
  `event_queue_time_min` int(10) unsigned,
  `event_queue_time_max` int(10) unsigned,
  `event_queue_time_mean` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_event_insid_day2` (`instance_id`),
  KEY `idx_event_ts_day2` (`timestamp`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_event_metrics_day3` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `event_name` varchar(255) NOT NULL,
  `event_type` varchar(255),
  `event_source` varchar(255),
  `app_name` varchar(255),
  `instance_id` varchar(35) NOT NULL,
  `subscribers_count` int(10) unsigned,
  `queued_count` int(10) unsigned,
  `processed_count` int(10) unsigned,
  `subscribers_error_count` int(10) unsigned,
  `event_delivery_time_min` int(10) unsigned,
  `event_delivery_time_max` int(10) unsigned,
  `event_delivery_time_mean` int(10) unsigned,
  `event_queue_time_min` int(10) unsigned,
  `event_queue_time_max` int(10) unsigned,
  `event_queue_time_mean` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_event_insid_day3` (`instance_id`),
  KEY `idx_event_ts_day3` (`timestamp`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_event_metrics_day4` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `event_name` varchar(255) NOT NULL,
  `event_type` varchar(255),
  `event_source` varchar(255),
  `app_name` varchar(255),
  `instance_id` varchar(35) NOT NULL,
  `subscribers_count` int(10) unsigned,
  `queued_count` int(10) unsigned,
  `processed_count` int(10) unsigned,
  `subscribers_error_count` int(10) unsigned,
  `event_delivery_time_min` int(10) unsigned,
  `event_delivery_time_max` int(10) unsigned,
  `event_delivery_time_mean` int(10) unsigned,
  `event_queue_time_min` int(10) unsigned,
  `event_queue_time_max` int(10) unsigned,
  `event_queue_time_mean` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_event_insid_day4` (`instance_id`),
  KEY `idx_event_ts_day4` (`timestamp`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_event_metrics_day5` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `event_name` varchar(255) NOT NULL,
  `event_type` varchar(255),
  `event_source` varchar(255),
  `app_name` varchar(255),
  `instance_id` varchar(35) NOT NULL,
  `subscribers_count` int(10) unsigned,
  `queued_count` int(10) unsigned,
  `processed_count` int(10) unsigned,
  `subscribers_error_count` int(10) unsigned,
  `event_delivery_time_min` int(10) unsigned,
  `event_delivery_time_max` int(10) unsigned,
  `event_delivery_time_mean` int(10) unsigned,
  `event_queue_time_min` int(10) unsigned,
  `event_queue_time_max` int(10) unsigned,
  `event_queue_time_mean` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_event_insid_day5` (`instance_id`),
  KEY `idx_event_ts_day5` (`timestamp`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_event_metrics_day6` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `event_name` varchar(255) NOT NULL,
  `event_type` varchar(255),
  `event_source` varchar(255),
  `app_name` varchar(255),
  `instance_id` varchar(35) NOT NULL,
  `subscribers_count` int(10) unsigned,
  `queued_count` int(10) unsigned,
  `processed_count` int(10) unsigned,
  `subscribers_error_count` int(10) unsigned,
  `event_delivery_time_min` int(10) unsigned,
  `event_delivery_time_max` int(10) unsigned,
  `event_delivery_time_mean` int(10) unsigned,
  `event_queue_time_min` int(10) unsigned,
  `event_queue_time_max` int(10) unsigned,
  `event_queue_time_mean` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_event_insid_day6` (`instance_id`),
  KEY `idx_event_ts_day6` (`timestamp`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_event_metrics_day7` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `event_name` varchar(255) NOT NULL,
  `event_type` varchar(255),
  `event_source` varchar(255),
  `app_name` varchar(255),
  `instance_id` varchar(35) NOT NULL,
  `subscribers_count` int(10) unsigned,
  `queued_count` int(10) unsigned,
  `processed_count` int(10) unsigned,
  `subscribers_error_count` int(10) unsigned,
  `event_delivery_time_min` int(10) unsigned,
  `event_delivery_time_max` int(10) unsigned,
  `event_delivery_time_mean` int(10) unsigned,
  `event_queue_time_min` int(10) unsigned,
  `event_queue_time_max` int(10) unsigned,
  `event_queue_time_mean` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_event_insid_day7` (`instance_id`),
  KEY `idx_event_ts_day7` (`timestamp`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_event_metrics_day8` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `event_name` varchar(255) NOT NULL,
  `event_type` varchar(255),
  `event_source` varchar(255),
  `app_name` varchar(255),
  `instance_id` varchar(35) NOT NULL,
  `subscribers_count` int(10) unsigned,
  `queued_count` int(10) unsigned,
  `processed_count` int(10) unsigned,
  `subscribers_error_count` int(10) unsigned,
  `event_delivery_time_min` int(10) unsigned,
  `event_delivery_time_max` int(10) unsigned,
  `event_delivery_time_mean` int(10) unsigned,
  `event_queue_time_min` int(10) unsigned,
  `event_queue_time_max` int(10) unsigned,
  `event_queue_time_mean` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_event_insid_day8` (`instance_id`),
  KEY `idx_event_ts_day8` (`timestamp`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `server_event_metrics_day9` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `event_name` varchar(255) NOT NULL,
  `event_type` varchar(255),
  `event_source` varchar(255),
  `app_name` varchar(255),
  `instance_id` varchar(35) NOT NULL,
  `subscribers_count` int(10) unsigned,
  `queued_count` int(10) unsigned,
  `processed_count` int(10) unsigned,
  `subscribers_error_count` int(10) unsigned,
  `event_delivery_time_min` int(10) unsigned,
  `event_delivery_time_max` int(10) unsigned,
  `event_delivery_time_mean` int(10) unsigned,
  `event_queue_time_min` int(10) unsigned,
  `event_queue_time_max` int(10) unsigned,
  `event_queue_time_mean` int(10) unsigned,
  `timestamp` timestamp NOT NULL,
  KEY `idx_event_insid_day9` (`instance_id`),
  KEY `idx_event_ts_day9` (`timestamp`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;